### PR TITLE
Update dependencies

### LINKED ISSUE #25: dependency on github.com/go-sql-driver/mysql v1.3.0 is old
The dependency on the Go mysql driver is very old.

The mysql-tester depends on strict mode to fetch warnings, which has since been removed: https://github.com/go-sql-driver/mysql/wiki/strict-mode

### PR DESCRIPTION
**Pull request by dveeden**
The biggest change is that the MySQL driver removed [`strict-mode`](https://github.com/go-sql-driver/mysql/wiki/strict-mode) which changes how warnings are handled.

Closes #25

### CODE REVIEW

**Comment by dveeden** [comment]
This is making similar changes as #33 except for the actual GBK part

**Comment by zimulala** [comment]
It seems this PR and https://github.com/pingcap/mysql-tester/pull/33 content is repeated.

**Comment by dveeden** [comment]
Not closing this as planned, even while #33 has been merged.

This updates a few more deps and fixes the regression from #33:
```
[dvaneeden@dve-carbon mysql-tester]$ git rev-parse HEAD
33200960bc1486259caceae3ceb08b346c39e9f6
[dvaneeden@dve-carbon mysql-tester]$ make build
go build -o mysql-tester ./src
# github.com/pingcap/mysql-tester/src
src/main.go:148:26: undefined: mysql
make: *** [Makefile:6: build] Error 2
[dvaneeden@dve-carbon mysql-tester]$ git checkout update_deps 
Switched to branch 'update_deps'
Your branch is up to date with 'origin/update_deps'.
[dvaneeden@dve-carbon mysql-tester]$ git rev-parse HEAD
0ee1edf56e749a58fe3399e8b884751c7b36bf3d
[dvaneeden@dve-carbon mysql-tester]$ make build
go build -o mysql-tester ./src
[dvaneeden@dve-carbon mysql-tester]$
```

/cc @zimulala @bb7133 @morgo

**Comment by morgo** [comment]
LGTM

(I don't think I have review privileges in this repo.)

**Review by zimulala — APPROVED** [review]
LGTM

**Review by hawkingrei — APPROVED** [review]
LGTM
