### PR TITLE
mysql-tester/src: fix build

### PR DESCRIPTION
**Pull request by morgo**
This fixes the following error:
```
/home/morgo/go/pkg/mod/github.com/pingcap/mysql-tester@v0.0.0-20211122021422-33200960bc14/src/main.go:148:26: undefined: mysql
```

It was introduced in https://github.com/pingcap/mysql-tester/pull/33

### CODE REVIEW

**Comment by dveeden** [comment]
Maybe #37 instead?

**Review by dveeden — APPROVED** [review]

**Comment by morgo** [comment]
OK, let me close this PR then. Thanks for working on this already!
